#include <iostream>
#include <fstream>
#include <cstring>
#include <iomanip>
using namespace std;

class Prefix; //Forward declarion of class Prefix to let this object know that class Prefix exists somewhire in this program....

class EAN{    //Class EAN to hold user define variable as one......
	char dec;  //Saves style which needs to be applied to the ean when displaying....
	char ean[14]; //Holds user input ISBN number....
	char area[6]; //Holds area of the book.......
	char publisher[8]; //Holds publisher of the book.......
	char title[7];  //Holds title of the book......
	char style_ean[18]; //Holds ISBN number with style included........
public:
	EAN(); //EAN safe empty safe Constructor......
	EAN(const char* str, const Prefix& list); //EAN constructor with two parameters then work with ean using Prefix reference to find detail information about ISBN....
	bool read(std::istream& is, const Prefix& list); //Gets book ISBN number from user......
	bool isRegistered(const Prefix& list); //Checks if ISBN number is registered or not if registered extracts area, title, publisher from ISBN using Prefix reference.....
	bool empty() const; //Returns true or false if object is in safe empty state.....
	bool isRegistered() const; //Returns true or false according to object's area, publisher and title is is empty or not......
	void style(char); //Receives style needed to enter for style_ean and calls toStr or toStrwithStyle according to if object is registered.....
	void toStr(char* str) const; //Copies ISBN number in to passed instr.....
	void toStrWithStyle(char* str) const; //Copies area, title, publisher, and etc to passed in str with adding style in between......
	void display(std::ostream& os) const; //Displays style_ean or ean according to if object is registered or not.....
};
bool isValid(const char* str); //Global function, validates passed in string........
bool operator==(const EAN& left, const EAN& right); //Checks if left EAN object on the left is same as right EAN object.....
std::ostream& operator<<(std::ostream& os, const EAN& ean); //Helper function to help display EAN object and returns output stream....